version: '3'

services:
  django:
    build:
      context: ./Eve_project
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Eve_project:/app
    depends_on:
      - angular

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
