# Generated by Django 5.0.1 on 2024-01-31 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Energies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy_type',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('pourcentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Energy_mean',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('pourcentage', models.IntegerField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Energies.energy_type')),
            ],
        ),
    ]
