# Generated by Django 5.0.1 on 2024-02-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Energies', '0002_energy_type_energy_mean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energy_mean',
            old_name='pourcentage',
            new_name='Energie_Totale',
        ),
        migrations.RenameField(
            model_name='energy_type',
            old_name='pourcentage',
            new_name='Energie_Totale',
        ),
    ]
