# Generated by Django 5.0.1 on 2024-02-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Energies', '0004_rename_energie_totale_energy_mean_pourcentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy_mean',
            name='Energie_toale',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energy_type',
            name='Energie_toale',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
