# Generated by Django 5.0.1 on 2024-02-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Energies', '0005_energy_mean_energie_toale_energy_type_energie_toale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy_mean',
            name='Energie_toale',
        ),
        migrations.RemoveField(
            model_name='energy_type',
            name='Energie_toale',
        ),
    ]
