# Generated by Django 5.0.1 on 2024-02-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Energies', '0006_remove_energy_mean_energie_toale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy_type',
            name='Energie_totale',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
