# Generated by Django 5.0.1 on 2024-02-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Energies', '0008_energie_group_energy_mean_group_energy_type_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='energie',
            name='chaleur',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energie',
            name='combustible',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energie',
            name='electricite',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
