# Generated by Django 5.0.1 on 2024-03-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Energies', '0010_energie_acteurs_principaux_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy_vector',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('pourcentage', models.IntegerField()),
                ('Energie_totale', models.IntegerField()),
            ],
        ),
    ]
