# Generated by Django 4.2.9 on 2024-03-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Energies', '0011_energy_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='energie',
            name='cout_du_combustible',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
