# Generated by Django 4.2.9 on 2024-03-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Energies', '0012_energie_cout_du_combustible'),
    ]

    operations = [
        migrations.AddField(
            model_name='energie',
            name='CO2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energie',
            name='densite_massique',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='energie',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='energie',
            name='idee_recue',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='energie',
            name='points_negatifs',
            field=models.CharField(max_length=1000),
        ),
    ]
